In [2]:
import numpy as np

Broadcasting allows us to carry operations on all the elements in an array without having to loop over each one

In [2]:
# arange fucnction to print a range of numbers
a = np.arange(4)
a

array([0, 1, 2, 3])

In [3]:
# adding to a matrix, adds to all values
a + 10

array([10, 11, 12, 13])

In [5]:
# multiplying a matrix
a * 10

array([ 0, 10, 20, 30])

Boolean Arrays